format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = "$cmd_duration"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = "\uE0A0 "
style = "bold purple"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 10
format = "[$duration]($style)"
style = "dimmed white"
show_milliseconds = true

[python]
symbol = " "
format = "[$symbol$virtualenv]($style) "

[nodejs]
symbol = " "

[golang]
symbol = " "

[character]
success_symbol = "[→](green)"
error_symbol = "[→](red)"
