brew "atuin"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "eza"
brew "fd"
brew "gh"
brew "git-lfs"
brew "just"
brew "lazygit"
brew "tsonglew/dutis/dutis"
brew "tokei"

# Rust CLI tools
tap "yvgude/lean-ctx"
brew "zoxide"
brew "fresh-editor"
brew "gitoxide"
brew "nushell"
brew "starship"
brew "typos-cli"
brew "typst"
brew "watchexec"
brew "serie"
brew "worktrunk"
brew "yvgude/lean-ctx/lean-ctx"

cask "ghostty"
cask "font-jetbrains-mono-nerd-font"
